import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar/navbar'
import '@fortawesome/fontawesome-free/css/all.min.css'
import 'bootstrap/dist/css/bootstrap.min.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'One Chemics',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Navbar/>
        
        {children}
      
      </body>

    </html>
  )
}
